modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="[32,)" #mandatory

authors="spacebyte" #optional

[[mods]] #mandatory

modId="letmespeak" #mandatory

version="${file.jarVersion}" #mandatory

displayName="LetMeSpeak" #mandatory

# The description text for the mod (multi line!) (#mandatory)
description='''
Prevents chat interruptions.
'''